### ISSUE TITLE
在github page 設定完 Custom domain 後，新的 push 會使 Custom domain 消失

### ISSUE THREAD

**Issue by shdennlin** [onejar99/demo-build-and-publish-gitbook#1]
您好，最近在設定自己的 gitbook, 參考完你的文章後受益良多，但由於對 gihub page 及 github action 的機制不是很了解，想要請教一下:

我依照你給的 `build.yaml` 建立完 `yaml` 檔後(如下), 可以成功建立 gitbook, 但每次再去 setting -> page 設定完 custom domain 後(ex: leetcode.shdennlin.com)，當下是可以 chame 成功的，但在新的 commit push上github時，custom domain 就會消失，會變成github預設的 shdennlin.github.io/leetcode ，想請教該如何在 github 的 workflow 解決，謝謝

``` yaml
name: Build and Publish My GitBook

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}
      USER_NAME   : shdennlin
      USER_EMAIL  : shawndennislin@gmail.com
      BOOK_DIR    : .

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - run: npm i gitbook-plugin-sitemap

    - name: Build and Deploy 🚀
      uses: onejar99/gitbook-build-publish-action@v1.0.1
```
